name: Health Check

on:
  schedule:
    - cron: '0 7-23 * * *' # Runs every hour from 7 AM to 11 PM (23:00)
  workflow_dispatch: # Allow manual triggering

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Health Endpoint
        run: |
          curl -X GET https://mern-ecommerce-uote.onrender.com/api/health
