name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  mern-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Deploy to Vercel
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SERVER_PROJECT_ID: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          cd server
          npx vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_TEAM_ID --project $VERCEL_SERVER_PROJECT_ID
