name: Playwright Tests with Mockoon
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd client
          npm ci
      - name: Create .env file
        run: |
          cd client
          echo "API_URL=http://localhost:3000/api" > .env
      - name: Install Playwright Browsers
        run: |
          cd client
          npx playwright install --with-deps
      - name: Start Mockoon
        uses: mockoon/cli-action@v2
        with:
          version: "latest"
          data-file: "mock-server/mern-server-mock.json"
          port: 3000
      - name: Make test call
        run: curl -X GET http://localhost:3000/api/health
      - name: Run Playwright tests
        run: |
          cd client
          echo "baseURL: $(node -p "require('./playwright.config.js').default.use.baseURL")"
          npx playwright test --grep @mockoon
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
