name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test-live:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mot
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Playwright Browsers
        run: |
          cd client
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd client
          npx playwright test --grep @live
        env:
          CI: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
